import { useCallback, useEffect, useMemo, useState, type CSSProperties } from 'react'
import { MessageSquareReply, RefreshCw, Star } from 'lucide-react'
import api from '@/lib/api'
import { toastError, toastSuccess } from '@/lib/toast'

type Review = { id: string; platform: string; rating: number; comment: string | null; replied: boolean; replyText: string | null; createdAt: string; customer?: { firstName: string; lastName: string } | null }
type Stats = { total: number; avgRating: number; unreplied: number; byPlatform: Record<string, { count: number; avgRating: number }> }

export default function ReputationDataPage({ view = 'reviews' }: { view?: 'reviews' | 'replies' | 'stats' }) {
  const [reviews, setReviews] = useState<Review[]>([]); const [stats, setStats] = useState<Stats | null>(null); const [reply, setReply] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); try { const [a, b] = await Promise.all([api.get<Review[]>('/reputation/reviews'), api.get<Stats>('/reputation/stats')]); setReviews(a.data); setStats(b.data) } catch (error: any) { toastError(error?.response?.data?.message || 'Chargement impossible') } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const shown = useMemo(() => view === 'replies' ? reviews.filter((item) => !item.replied) : reviews, [reviews, view])
  async function sendReply(item: Review) { const text = (reply[item.id] || '').trim(); if (!text) return toastError('Écrivez une réponse'); try { await api.put(`/reputation/reviews/${item.id}/reply`, { replyText: text }); setReply((value) => ({ ...value, [item.id]: '' })); await load(); toastSuccess('Réponse enregistrée') } catch (error: any) { toastError(error?.response?.data?.message || 'Réponse impossible') } }
  return <main style={page}><header style={header}><div><p style={eyebrow}>Réputation</p><h1 style={title}>{view === 'stats' ? 'Statistiques des avis' : view === 'replies' ? 'Avis à répondre' : 'Avis clients'}</h1><p style={subtitle}>Seuls les avis présents dans votre base sont affichés.</p></div><button onClick={() => void load()} style={secondary}><RefreshCw size={16} /> Actualiser</button></header><section style={statsGrid}><Stat label="Avis" value={stats?.total ?? 0} /><Stat label="Note moyenne" value={`${stats?.avgRating ?? 0} / 5`} /><Stat label="Sans réponse" value={stats?.unreplied ?? 0} /></section>{view === 'stats' && <section style={card}><h2 style={h2}>Par plateforme</h2>{!stats || Object.keys(stats.byPlatform).length === 0 ? <Empty text="Aucune statistique disponible." /> : Object.entries(stats.byPlatform).map(([platform, value]) => <article key={platform} style={row}><strong>{platform}</strong><span>{value.count} avis · {value.avgRating.toFixed(1)} / 5</span></article>)}</section>}{view !== 'stats' && <section style={card}>{loading ? <Empty text="Chargement…" /> : shown.length === 0 ? <Empty text={view === 'replies' ? 'Tous les avis ont une réponse.' : 'Aucun avis enregistré.'} /> : shown.map((item) => <article key={item.id} style={{ ...row, alignItems: 'stretch', flexDirection: 'column' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12 }}><div><strong>{item.customer ? `${item.customer.firstName} ${item.customer.lastName}` : 'Client'} · {item.platform}</strong><div style={small}>{new Date(item.createdAt).toLocaleString('fr-LU')}</div></div><span style={stars}><Star size={15} fill="currentColor" /> {item.rating}/5</span></div><p style={{ margin: 0, color: '#334155' }}>{item.comment || 'Aucun commentaire.'}</p>{item.replied ? <div style={replyBox}><strong>Votre réponse</strong><div>{item.replyText}</div></div> : <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}><input aria-label={`Répondre à l'avis ${item.id}`} value={reply[item.id] || ''} onChange={(e) => setReply((value) => ({ ...value, [item.id]: e.target.value }))} placeholder="Votre réponse publique" style={{ ...input, flex: '1 1 300px' }} /><button onClick={() => void sendReply(item)} style={primary}><MessageSquareReply size={16} /> Enregistrer</button></div>}</article>)}</section>}</main>
}
function Stat({ label, value }: { label: string; value: string | number }) { return <div style={{ ...card, margin: 0 }}><span style={small}>{label}</span><strong style={{ display: 'block', fontSize: 25 }}>{value}</strong></div> }
function Empty({ text }: { text: string }) { return <div style={{ padding: 28, textAlign: 'center', color: '#64748b', background: '#f8fafc', borderRadius: 12 }}>{text}</div> }
const page: CSSProperties = { maxWidth: 1050, margin: '0 auto', padding: '26px 20px 50px', color: '#0f172a' }, header: CSSProperties = { display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'flex-start', flexWrap: 'wrap', marginBottom: 20 }, eyebrow: CSSProperties = { margin: 0, color: '#be185d', fontSize: 12, fontWeight: 850, textTransform: 'uppercase', letterSpacing: '.1em' }, title: CSSProperties = { margin: '4px 0 0', fontSize: 32, letterSpacing: '-.03em' }, subtitle: CSSProperties = { color: '#64748b', margin: '7px 0 0' }, card: CSSProperties = { background: '#fff', border: '1px solid #e2e8f0', borderRadius: 18, padding: 18, boxShadow: '0 8px 28px rgba(15,23,42,.05)', marginBottom: 16 }, statsGrid: CSSProperties = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(170px,1fr))', gap: 12, marginBottom: 16 }, h2: CSSProperties = { margin: '0 0 14px', fontSize: 18 }, row: CSSProperties = { padding: 13, border: '1px solid #e2e8f0', borderRadius: 12, display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center', marginTop: 8, flexWrap: 'wrap' }, small: CSSProperties = { color: '#64748b', fontSize: 12 }, stars: CSSProperties = { color: '#b45309', display: 'inline-flex', gap: 4, alignItems: 'center', fontWeight: 800 }, replyBox: CSSProperties = { padding: 12, borderRadius: 10, background: '#f8fafc', color: '#475569', fontSize: 13 }, input: CSSProperties = { border: '1px solid #cbd5e1', borderRadius: 9, padding: '9px 10px', color: '#0f172a', background: '#fff', font: 'inherit' }, primary: CSSProperties = { border: 0, borderRadius: 9, padding: '9px 13px', background: '#be185d', color: '#fff', fontWeight: 750, cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: 6 }, secondary: CSSProperties = { ...primary, background: '#fff', color: '#334155', border: '1px solid #cbd5e1' }
