import { chromium } from '@playwright/test'
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('dialog', (d) => d.dismiss().catch(() => {}))
await page.goto('http://localhost:5174/login', { waitUntil: 'domcontentloaded' })
await page.evaluate(() => { localStorage.setItem('creorga-onboarded', '1'); localStorage.setItem('creorga.onboardingDone', String(Date.now())) })
await page.locator('input[type="email"]').fill('admin@creorga.local')
await page.locator('input[placeholder="••••••••"]').fill('Admin1234!')
await page.locator('button[type="submit"]').click()
await page.waitForURL('**/welcome')
await page.goto('http://localhost:5174/pos/floor', { waitUntil: 'domcontentloaded' })
await page.waitForTimeout(1500)
await page.getByText('T3', { exact: false }).first().click()
await page.waitForTimeout(700)
await page.getByText('+ Chaise', { exact: false }).first().click()
await page.waitForTimeout(700)
await page.getByText('Ch1', { exact: false }).first().click()
await page.waitForTimeout(800)
// ajoute 2 cafés + 1 burger
await page.getByText('Café', { exact: false }).first().click().catch(()=>{})
await page.waitForTimeout(400)
await page.getByText('Café', { exact: false }).first().click().catch(()=>{})
await page.waitForTimeout(400)
await page.getByText('Burger', { exact: false }).first().click().catch(()=>{})
await page.waitForTimeout(800)
await page.screenshot({ path: 'tests-qa/vision/order-05-items.png' })
const txt = await page.evaluate(() => document.body.innerText.replace(/\s+/g,' '))
const m = txt.match(/TOTAL CHAISE ([\d.,]+ ?€)/i)
console.log('Total chaise après 2 cafés + 1 burger:', m ? m[1] : '(non trouvé)', '| attendu ~10.10€')
console.log('COMMANDE compte:', (txt.match(/COMMANDE \((\d+)\)/)||[])[1])
await browser.close()
