import { chromium } from '@playwright/test'
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('dialog', (d) => d.dismiss().catch(() => {}))
await page.goto('http://localhost:5174/login', { waitUntil: 'domcontentloaded' })
await page.evaluate(() => { localStorage.setItem('creorga-onboarded', '1'); localStorage.setItem('creorga.onboardingDone', String(Date.now())) })
await page.locator('input[type="email"]').fill('admin@creorga.local')
await page.locator('input[placeholder="••••••••"]').fill('Admin1234!')
await page.locator('button[type="submit"]').click()
await page.waitForURL('**/welcome')
await page.goto('http://localhost:5174/pos/floor', { waitUntil: 'domcontentloaded' })
await page.waitForTimeout(1500)
await page.getByText('T2', { exact: false }).first().click()
await page.waitForTimeout(800)
await page.getByText('+ Chaise', { exact: false }).first().click()
await page.waitForTimeout(800)
// clic sur la ligne Ch1 pour l'ouvrir
await page.getByText('Ch1', { exact: false }).first().click().catch(()=>{})
await page.waitForTimeout(1000)
await page.screenshot({ path: 'tests-qa/vision/order-04-chair-open.png' })
const txt = await page.evaluate(() => document.body.innerText.replace(/\s+/g,' '))
console.log('Après clic Ch1, mots-clés:', ['Ajouter','Menu','Boisson','Plat','Carte','article','€'].filter(k=>txt.includes(k)).join(', '))
await browser.close()
