import { chromium } from '@playwright/test'
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('dialog', (d) => d.dismiss().catch(() => {}))
await page.goto('http://localhost:5174/login', { waitUntil: 'domcontentloaded' })
await page.evaluate(() => { localStorage.setItem('creorga-onboarded', '1'); localStorage.setItem('creorga.onboardingDone', String(Date.now())) })
await page.locator('input[type="email"]').fill('admin@creorga.local')
await page.locator('input[placeholder="••••••••"]').fill('Admin1234!')
await page.locator('button[type="submit"]').click()
await page.waitForURL('**/welcome')
async function test(route, label, sel) {
  await page.goto('http://localhost:5174'+route, { waitUntil: 'domcontentloaded' })
  await page.waitForTimeout(1400)
  const before = await page.evaluate(() => document.body.innerHTML.length)
  await page.getByText(sel, { exact: false }).first().click({ timeout: 3000 }).catch((e)=>console.log(label,'clic échec'))
  await page.waitForTimeout(1000)
  const after = await page.evaluate(() => document.body.innerHTML.length)
  const url = page.url().replace('http://localhost:5174','')
  console.log(`${label}: ΔDOM=${after-before}, URL=${url}`)
  await page.screenshot({ path: `tests-qa/vision/inv-${label}.png` })
}
await test('/invoices/devis', 'nouveau-devis', 'Nouveau devis')
await test('/invoices/devis', 'comparer', 'Comparer')
await browser.close()
