import { chromium } from '@playwright/test'
const ROUTE=process.env.ROUTE, LABEL=process.env.LABEL, NAME=process.env.NAME||'tap'
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('dialog', (d) => { console.log('DIALOG:', d.message().slice(0,80)); d.dismiss().catch(()=>{}) })
await page.goto('http://localhost:5174/login', { waitUntil: 'domcontentloaded' })
await page.evaluate(() => { localStorage.setItem('creorga-onboarded','1'); localStorage.setItem('creorga.onboardingDone', String(Date.now())) })
await page.locator('input[type="email"]').fill('admin@creorga.local')
await page.locator('input[placeholder="••••••••"]').fill('Admin1234!')
await page.locator('button[type="submit"]').click()
await page.waitForURL('**/welcome')
await page.goto('http://localhost:5174'+ROUTE, { waitUntil: 'domcontentloaded' })
await page.waitForTimeout(1500)
const b = await page.evaluate(() => document.body.innerHTML.length)
const el = page.getByText(LABEL, { exact: false }).first()
await el.scrollIntoViewIfNeeded().catch(()=>{})
await el.click({ timeout: 3000 }).catch((e)=>console.log('clic échec:', e.message.slice(0,50)))
await page.waitForTimeout(1200)
const a = await page.evaluate(() => document.body.innerHTML.length)
console.log(`"${LABEL}": ΔDOM=${a-b}, URL=${page.url().replace('http://localhost:5174','')}`)
await page.screenshot({ path: `tests-qa/vision/${NAME}.png` })
await browser.close()
