import { chromium } from '@playwright/test'
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('http://localhost:5174/login', { waitUntil: 'domcontentloaded' })
await page.evaluate(() => { localStorage.setItem('creorga-onboarded','1'); localStorage.setItem('creorga.onboardingDone', String(Date.now())) })
await page.locator('input[type="email"]').fill('admin@creorga.local')
await page.locator('input[placeholder="••••••••"]').fill('Admin1234!')
await page.locator('button[type="submit"]').click()
await page.waitForURL('**/welcome')
await page.goto('http://localhost:5174/reputation', { waitUntil: 'domcontentloaded' })
await page.waitForTimeout(1500)
const count = () => page.evaluate(() => document.body.innerText.match(/(\d+) avis affichés/)?.[1])
console.log('Initial:', await count(), 'avis affichés')
await page.getByText('1★', { exact: true }).first().click()
await page.waitForTimeout(800)
console.log('Après filtre 1★:', await count(), 'avis affichés')
await page.getByText('Non répondu', { exact: false }).first().click()
await page.waitForTimeout(800)
console.log('Après +Non répondu:', await count(), 'avis affichés')
await page.screenshot({ path: 'tests-qa/vision/rep-filter.png' })
await browser.close()
